language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/
    - /^patch-.*$/

php:
    - 7.0
    - 7.1
    - hhvm
env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=2.7.*

install:
    - travis_retry composer update --prefer-dist --no-interaction

script:
    - $TEST_COMMAND
